# Generated by Django 3.1.7 on 2022-02-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0004_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='posX',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='posY',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='row',
            field=models.IntegerField(null=True),
        ),
    ]
