# Generated by Django 3.1.7 on 2022-02-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0005_auto_20220213_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_id', models.CharField(max_length=20, unique=True)),
                ('sequence_id', models.IntegerField()),
            ],
        ),
    ]
