# Generated by Django 3.1.7 on 2022-02-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0007_location_floor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('capacity', models.IntegerField()),
                ('building_enum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtls_app.enumeration')),
            ],
        ),
    ]
