# Generated by Django 3.1.7 on 2022-02-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0010_module_location_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('nationalid', models.IntegerField(unique=True)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtls_app.asset', unique=True)),
                ('gender_enum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtls_app.enumeration')),
            ],
        ),
    ]
