# Generated by Django 3.1.7 on 2022-02-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0011_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
    ]
