# Generated by Django 3.1.7 on 2022-02-13 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0014_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtls_app.asset', unique=True)),
                ('type_enum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtls_app.enumeration')),
            ],
        ),
    ]
