# Generated by Django 3.1.7 on 2022-02-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0015_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtls_app.floor')),
                ('zone_enum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtls_app.enumeration')),
            ],
        ),
    ]
