# Generated by Django 3.1.7 on 2022-02-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0016_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.CharField(max_length=20, unique=True)),
                ('count', models.IntegerField()),
                ('fromDate', models.DateTimeField()),
                ('tillDate', models.DateTimeField()),
                ('volume', models.IntegerField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtls_app.location')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtls_app.stock')),
            ],
        ),
    ]
