# Generated by Django 3.1.7 on 2022-02-13 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0017_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResponsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=20, unique=True)),
                ('fromDate', models.DateTimeField()),
                ('tillDate', models.DateTimeField()),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtls_app.asset')),
            ],
        ),
        migrations.DeleteModel(
            name='TagPosition',
        ),
    ]
