# Generated by Django 3.1.7 on 2022-02-13 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0018_auto_20220213_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('posX', models.FloatField(null=True)),
                ('posY', models.FloatField(null=True)),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtls_app.floor')),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtls_app.module')),
            ],
            options={
                'unique_together': {('timestamp', 'module_id')},
            },
        ),
    ]
