# Generated by Django 3.1.7 on 2022-02-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0019_tagposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('orderDate', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('data', models.CharField(max_length=100)),
                ('category_enum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_enums', to='rtls_app.enumeration')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtls_app.task')),
                ('priority_enum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_enums', to='rtls_app.enumeration')),
                ('status_enum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_enums', to='rtls_app.enumeration')),
            ],
        ),
    ]
