# Generated by Django 3.1.7 on 2022-02-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0021_auto_20220226_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.IntegerField(default=0)),
                ('fromDate', models.DateTimeField()),
                ('tillDate', models.DateTimeField()),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtls_app.asset')),
            ],
        ),
    ]
