# Generated by Django 3.1.7 on 2022-02-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0022_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresponsible',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtls_app.task', unique=True),
        ),
        migrations.AddField(
            model_name='taskresponsible',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtls_app.task'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtls_app.unit'),
        ),
    ]
