# Generated by Django 3.1.7 on 2022-02-26 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0024_child_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='capacity',
        ),
    ]
