# Generated by Django 3.1.7 on 2022-03-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0026_auto_20220309_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_id',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=35),
        ),

    ]
