# Generated by Django 3.1.7 on 2022-03-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0027_auto_20220309_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='dates',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
