# Generated by Django 3.1.7 on 2022-03-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0029_auto_20220309_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
