# Generated by Django 3.1.7 on 2022-03-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0032_auto_20220309_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum_id', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
