# Generated by Django 3.1.7 on 2022-03-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0037_auto_20220309_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='posX',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='posY',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='row',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
