# Generated by Django 3.1.7 on 2022-03-09 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0039_auto_20220309_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zone_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rtls_app.zone'),
            preserve_default=False,
        ),
    ]
