# Generated by Django 3.1.7 on 2022-03-09 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0040_auto_20220309_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtls_app.zone'),
        ),
    ]
