# Generated by Django 3.1.7 on 2022-03-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0041_auto_20220309_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='fromDate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='tillDate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
