# Generated by Django 3.1.7 on 2022-03-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0044_auto_20220310_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
