# Generated by Django 3.1.7 on 2022-03-10 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0045_auto_20220310_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category_enum_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_category_enums', to='rtls_app.enumeration'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority_enum_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_priority_enums', to='rtls_app.enumeration'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status_enum_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_status_enums', to='rtls_app.enumeration'),
        ),
    ]
