# Generated by Django 3.1.7 on 2022-03-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0046_auto_20220310_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskresponsible',
            name='asset_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtls_app.asset'),
        ),
        migrations.AlterField(
            model_name='taskresponsible',
            name='fromDate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskresponsible',
            name='tillDate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
