# Generated by Django 3.1.7 on 2022-04-15 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtls_app', '0048_auto_20220310_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtls_app.location'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='stock_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtls_app.stock'),
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTimestamp', models.IntegerField()),
                ('endTimestamp', models.IntegerField()),
                ('asset_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtls_app.asset')),
                ('fromBuilding_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromBuilding_id', to='rtls_app.building')),
                ('loadType_enum_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rtls_app.enumeration')),
                ('toBuilding_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toBuilding_id', to='rtls_app.building')),
            ],
        ),
    ]
